const fs = require('fs')
const path = require('path')

// Specify the input files and output file
const devInputFile = path.join(__dirname, 'modules.dev.json')
const prodInputFile = path.join(__dirname, 'modules.prod.json')
const outputFile = path.join(__dirname, 'public', 'host-config.js')

// Determine which input file to use based on NODE_ENV
const inputFile = process.env.NODE_ENV === 'production' ? prodInputFile : devInputFile

// Read the input file
fs.readFile(inputFile, 'utf8', (err, data) => {
    if (err) {
        console.error(`Error reading file from disk: ${inputFile}`, err)
        process.exit(1)
    }

    // Parse the JSON data from the input file
    let parsedData
    try {
        parsedData = JSON.parse(data)
    } catch (err) {
        console.error(`Error parsing JSON data from file: ${inputFile}`, err)
        process.exit(1)
    }

    // Convert the parsed data back to a string, formatted as a JavaScript object
    const outputData = `/* WARNING: This file is automatically generated. Do not modify this file directly! */\nwindow._env_ = ${JSON.stringify(
        parsedData,
        null,
        4
    )}\n`

    // Write the output file
    fs.writeFile(outputFile, outputData, (err) => {
        if (err) {
            console.error(`Error writing file to disk: ${outputFile}`, err)
            process.exit(1)
        }

        console.log(`Successfully wrote file: ${outputFile}`)
    })
})
